Name: 'Sherry'
subset: 0.8
context: 20
archetype: 'pyramid'
activations: 'GELU'
learning_rate: 7.5e-4
dropout: 0.3
optimizers: 'AdamW'
scheduler: 'Mixed'
epochs: 5
batch_size: 768
weight_decay: 0.05
weight_initialization: "kaiming_normal"
augmentations: 'Both'
freq_mask_param: 12
time_mask_param: 12
r_drop_alpha: 3.0
grad_clip: 1.0
aug_prob: 0.7
